# Form implementation generated from reading ui file 'ribbon_dialog_4.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


import os

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        # Get the absolute path to the resources directory
        script_dir = os.path.dirname(os.path.abspath(__file__))
        gifs_dir = os.path.join(script_dir, "resources", "gifs")
        Dialog.setObjectName("Dialog")
        Dialog.resize(261, 257)
        self.verticalSlider = QtWidgets.QSlider(parent=Dialog)
        self.verticalSlider.setGeometry(QtCore.QRect(10, 10, 16, 74))
        self.verticalSlider.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.horizontalSlider = QtWidgets.QSlider(parent=Dialog)
        self.horizontalSlider.setGeometry(QtCore.QRect(80, 90, 84, 16))
        self.horizontalSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(40, 220, 160, 26))
        self.buttonBox.setStandardButtons(
            QtWidgets.QDialogButtonBox.StandardButton.Cancel | QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.layoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.layoutWidget1 = QtWidgets.QWidget(parent=Dialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(70, 120, 101, 82))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_t = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.label_t.setObjectName("label_t")
        self.gridLayout.addWidget(self.label_t, 0, 0, 1, 1)
        self.lineEdit_t = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        self.lineEdit_t.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_t.setObjectName("lineEdit_t")
        self.gridLayout.addWidget(self.lineEdit_t, 0, 1, 1, 1)
        self.label_w = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.label_w.setTextFormat(QtCore.Qt.TextFormat.MarkdownText)
        self.label_w.setObjectName("label_w")
        self.gridLayout.addWidget(self.label_w, 1, 0, 1, 1)
        self.lineEdit_w = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        self.lineEdit_w.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_w.setObjectName("lineEdit_w")
        self.gridLayout.addWidget(self.lineEdit_w, 1, 1, 1, 1)
        self.label_l = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.label_l.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_l.setObjectName("label_l")
        self.gridLayout.addWidget(self.label_l, 2, 0, 1, 1)
        self.lineEdit_l = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        self.lineEdit_l.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_l.setObjectName("lineEdit_l")
        self.gridLayout.addWidget(self.lineEdit_l, 2, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(parent=Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 10, 211, 71))
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.toolButton_L = QtWidgets.QToolButton(parent=self.groupBox_2)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(os.path.join(gifs_dir, "L_des.gif")), QtGui.QIcon.Mode.Active,
                       QtGui.QIcon.State.Off)
        icon.addPixmap(QtGui.QPixmap(os.path.join(gifs_dir, "L_sel.gif")), QtGui.QIcon.Mode.Active,
                       QtGui.QIcon.State.On)
        self.toolButton_L.setIcon(icon)
        self.toolButton_L.setIconSize(QtCore.QSize(48, 48))
        self.toolButton_L.setCheckable(True)
        self.toolButton_L.setObjectName("toolButton_L")
        self.horizontalLayout.addWidget(self.toolButton_L)
        self.toolButton_R = QtWidgets.QToolButton(parent=self.groupBox_2)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(os.path.join(gifs_dir, "R_des.gif")), QtGui.QIcon.Mode.Active,
                        QtGui.QIcon.State.Off)
        icon1.addPixmap(QtGui.QPixmap(os.path.join(gifs_dir, "R_sel.gif")), QtGui.QIcon.Mode.Active,
                        QtGui.QIcon.State.On)
        self.toolButton_R.setIcon(icon1)
        self.toolButton_R.setIconSize(QtCore.QSize(48, 48))
        self.toolButton_R.setCheckable(True)
        self.toolButton_R.setObjectName("toolButton_R")
        self.horizontalLayout.addWidget(self.toolButton_R)
        self.toolButton_M = QtWidgets.QToolButton(parent=self.groupBox_2)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(os.path.join(gifs_dir, "M_des.gif")), QtGui.QIcon.Mode.Active,
                        QtGui.QIcon.State.Off)
        icon2.addPixmap(QtGui.QPixmap(os.path.join(gifs_dir, "M_sel.gif")), QtGui.QIcon.Mode.Active,
                        QtGui.QIcon.State.On)
        self.toolButton_M.setIcon(icon2)
        self.toolButton_M.setIconSize(QtCore.QSize(48, 48))
        self.toolButton_M.setCheckable(True)
        self.toolButton_M.setChecked(True)
        self.toolButton_M.setObjectName("toolButton_M")
        self.horizontalLayout.addWidget(self.toolButton_M)
        self.toolButton_A = QtWidgets.QToolButton(parent=self.groupBox_2)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(os.path.join(gifs_dir, "A_des.gif")), QtGui.QIcon.Mode.Active,
                        QtGui.QIcon.State.Off)
        icon3.addPixmap(QtGui.QPixmap(os.path.join(gifs_dir, "A_sel.gif")), QtGui.QIcon.Mode.Active,
                        QtGui.QIcon.State.On)
        self.toolButton_A.setIcon(icon3)
        self.toolButton_A.setIconSize(QtCore.QSize(48, 48))
        self.toolButton_A.setCheckable(True)
        self.toolButton_A.setObjectName("toolButton_A")
        self.horizontalLayout.addWidget(self.toolButton_A)
        self.toolButton_W = QtWidgets.QToolButton(parent=self.groupBox_2)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(os.path.join(gifs_dir, "W_des.gif")), QtGui.QIcon.Mode.Active,
                        QtGui.QIcon.State.Off)
        icon4.addPixmap(QtGui.QPixmap(os.path.join(gifs_dir, "W_sel.gif")), QtGui.QIcon.Mode.Active,
                        QtGui.QIcon.State.On)
        self.toolButton_W.setIcon(icon4)
        self.toolButton_W.setIconSize(QtCore.QSize(48, 48))
        self.toolButton_W.setCheckable(True)
        self.toolButton_W.setObjectName("toolButton_W")
        self.horizontalLayout.addWidget(self.toolButton_W)
        self.label_t.setBuddy(self.lineEdit_t)
        self.label_w.setBuddy(self.lineEdit_w)
        self.label_l.setBuddy(self.lineEdit_l)

        self.activeRibbon = "M"

        self.toolButton_L.setAutoExclusive(True)
        self.toolButton_R.setAutoExclusive(True)
        self.toolButton_M.setAutoExclusive(True)
        self.toolButton_A.setAutoExclusive(True)
        self.toolButton_W.setAutoExclusive(True)

        self.toolButton_M.setChecked(True)
        self.lineEdit_t.setText("M")

        self.ribbonGroup = QtWidgets.QButtonGroup(Dialog)

        self.ribbonGroup.addButton(self.toolButton_L, 0)
        self.ribbonGroup.addButton(self.toolButton_R, 1)
        self.ribbonGroup.addButton(self.toolButton_M, 2)
        self.ribbonGroup.addButton(self.toolButton_A, 3)
        self.ribbonGroup.addButton(self.toolButton_W, 4)

        self.ribbonGroup.buttonToggled.connect(self.onRibbonToggled)

        self.verticalSlider.setMinimum(3)
        self.verticalSlider.setMaximum(120)
        self.verticalSlider.setPageStep(10)

        self.horizontalSlider.setMinimum(3)
        self.horizontalSlider.setMaximum(35)
        self.horizontalSlider.setPageStep(5)

        # self.lineEdit_w.textChanged.connect(self.live_clamp_width)
        # self.lineEdit_l.textChanged.connect(self.live_clamp_length)
        self.lineEdit_w.editingFinished.connect(self.fix_width)
        self.lineEdit_l.editingFinished.connect(self.fix_length)
        self.lineEdit_t.editingFinished.connect(self.set_tool_buttons_from_text)

        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)

        self.retranslateUi(Dialog)
        # self.horizontalSlider.valueChanged['int'].connect(self.lineEdit_w.copy) # type: ignore
        # self.verticalSlider.valueChanged['int'].connect(self.lineEdit_l.copy) # type: ignore
        self.horizontalSlider.valueChanged['int'].connect(self.update_w_from_slider)  # type: ignore
        self.verticalSlider.valueChanged['int'].connect(self.update_l_from_slider)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Define ribbon properties"))
        self.label_t.setText(_translate("Dialog", "Type"))
        self.label_w.setText(_translate("Dialog", "Width"))
        self.label_l.setText(_translate("Dialog", "Length"))
        self.groupBox_2.setTitle(_translate("Dialog", "Ribbon type"))
        self.toolButton_L.setText(_translate("Dialog", "..."))
        self.toolButton_R.setText(_translate("Dialog", "..."))
        self.toolButton_M.setText(_translate("Dialog", "..."))
        self.toolButton_A.setText(_translate("Dialog", "..."))
        self.label_t.setText(_translate("Dialog", "Type"))
        self.label_w.setText(_translate("Dialog", "Width"))
        self.label_l.setText(_translate("Dialog", "Length"))

    def onRibbonToggled(self, button, checked):
        if not checked:
            return  # only care about the button that became checked

        if button is self.toolButton_L:
            self.activeRibbon = "L"
        elif button is self.toolButton_R:
            self.activeRibbon = "R"
        elif button is self.toolButton_M:
            self.activeRibbon = "M"
        elif button is self.toolButton_A:
            self.activeRibbon = "A"
        elif button is self.toolButton_W:
            self.activeRibbon = "W"

        self.lineEdit_t.setText(self.activeRibbon)

        # For debugging:
        # print("Active ribbon:", self.activeRibbon)

    def update_l_from_slider(self, value):
        self.lineEdit_l.setText(str(value))

    def update_w_from_slider(self, value):
        self.lineEdit_w.setText(str(value))

    def set_tool_buttons_from_text(self):
        self.lineEdit_t.setText(self.lineEdit_t.text().upper())
        match self.lineEdit_t.text():
            case "L":
                self.toolButton_L.setChecked(True)
            case "R":
                self.toolButton_R.setChecked(True)
            case "M":
                self.toolButton_M.setChecked(True)
            case "A":
                self.toolButton_A.setChecked(True)
            case "W":
                self.toolButton_W.setChecked(True)
            case _:
                QMessageBox.warning(None, "Warning", "No valid type !")

    def fix_width(self):
        v = int(self.lineEdit_w.text() or 0)
        v = max(3, min(50, v))
        self.lineEdit_w.setText(str(v))
        v_int = int(v)
        self.horizontalSlider.setFocus()
        self.horizontalSlider.setValue(v_int)

    def fix_length(self):
        v = int(self.lineEdit_l.text() or 0)
        v = max(3, min(100, v))
        self.lineEdit_l.setText(str(v))
        v_int = int(v)
        self.verticalSlider.setFocus()
        self.verticalSlider.setValue(v_int)

    def live_clamp_width(self, text):
        if text.isdigit():
            v = int(text)
            if v > 35:
                self.lineEdit_w.setText("35")
            if v < 3:
                self.lineEdit_w.setText("3")

    def live_clamp_length(self, text):
        if text.isdigit():
            v = int(text)
            if v > 100:
                self.lineEdit_l.setText("120")
            if v < 3:
                self.lineEdit_l.setText("3")

    def get_values(self):
        # ribbon type from activeRibbon (set in onRibbonToggled)
        ribbon_type = getattr(self, "activeRibbon", None)

        # read and convert length + width (from line edits or sliders)
        try:
            length = int(self.lineEdit_l.text())
        except ValueError:
            QMessageBox.warning(None, "Warning", "Length parameter missing !")
            length = self.verticalSlider_h.value()
            return ()

        try:
            width = int(self.lineEdit_w.text())
        except ValueError:
            QMessageBox.warning(None, "Warning", "Width parameter missing !")
            width = self.horizontalSlider_w.value()
            return ()

        return ribbon_type, width, length


import sys
from PyQt6.QtWidgets import QApplication, QDialog


class RibbonDialog(QDialog):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.ui = Ui_Dialog()
        self.ui.setupUi(self)  # baut das UI in dieses QDialog ein


if __name__ == "__main__":
    app = QApplication(sys.argv)
    window = RibbonDialog()
    window.show()
    sys.exit(app.exec())
